### ISSUE TITLE
Unit test failures for CSharp expressions on Windows (compile error)

### ISSUE THREAD

**Issue by craigfowler** [csf-dev/ZPT-Sharp#169]
The following tests fail *on Windows only* when executing unit tests:

```
24 - CS0103:The name 'nameof' does not exist in the current context30 - CS0103:The name 'nameof' does not exist in the current context30 - CS0103:The name 'nameof' does not exist in the current context24 - CS0103:The name 'nameof' does not exist in the current context30 - CS0103:The name 'nameof' does not exist in the current context
Errors and Failures

1) Failed : Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.TestCSharpExpressionFactory
One or more child tests had errors

2) Error : Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.TestCSharpExpressionFactory.Create_returns_expression_which_may_be_executed_with_no_parameters
CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionExceptionException : The CSharp expression must be valid; there must not be any compilation errors raised.  Please check the validity of the expression code?
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionFactory.CompileHostAssembly(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\CSharpExpressionFactory.cs:line 99
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionFactory.Create(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\CSharpExpressionFactory.cs:line 27
   at Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.TestCSharpExpressionFactory.Create_returns_expression_which_may_be_executed_with_no_parameters() in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions\TestCSharpExpressionFactory.cs:line 59

3) Error : Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.TestCSharpExpressionFactory.Create_returns_expression_which_may_be_executed_with_some_parameters
CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionExceptionException : The CSharp expression must be valid; there must not be any compilation errors raised.  Please check the validity of the expression code?
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionFactory.CompileHostAssembly(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\CSharpExpressionFactory.cs:line 99
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionFactory.Create(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\CSharpExpressionFactory.cs:line 27
   at Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.TestCSharpExpressionFactory.Create_returns_expression_which_may_be_executed_with_some_parameters() in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions\TestCSharpExpressionFactory.cs:line 77

4) Error : Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.TestCSharpExpressionFactory.Create_returns_expression_which_may_be_executed_with_typed_parameters
CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionExceptionException : The CSharp expression must be valid; there must not be any compilation errors raised.  Please check the validity of the expression code?
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionFactory.CompileHostAssembly(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\CSharpExpressionFactory.cs:line 99
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionFactory.Create(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\CSharpExpressionFactory.cs:line 27
   at Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.TestCSharpExpressionFactory.Create_returns_expression_which_may_be_executed_with_typed_parameters() in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions\TestCSharpExpressionFactory.cs:line 101

5) Error : Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.TestCSharpExpressionFactory.Create_returns_non_null_with_no_parameters
CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionExceptionException : The CSharp expression must be valid; there must not be any compilation errors raised.  Please check the validity of the expression code?
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionFactory.CompileHostAssembly(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\CSharpExpressionFactory.cs:line 99
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionFactory.Create(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\CSharpExpressionFactory.cs:line 27
   at Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.TestCSharpExpressionFactory.Create_returns_non_null_with_no_parameters() in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions\TestCSharpExpressionFactory.cs:line 46

6) Failed : Test.CSF.Zpt.Integration.ZptIntegrationTests
One or more child tests had errors

7) Failed : Test.CSF.Zpt.Integration.ZptIntegrationTests.RunIntegrationTests
  Out of 45 integration tests, 1 failed. See the log file for more info.
  Expected: True
  But was:  False
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Integration.ZptIntegrationTests.RunIntegrationTests() in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt.Integration\ZptIntegrationTests.cs:line 39

Test Run Summary
  Overall result: Failed
  Test Count: 331, Passed: 326, Failed: 5, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 1, Errors: 4, Invalid: 0
  Start time: 2016-11-15 13:17:17Z
    End time: 2016-11-15 13:17:22Z
    Duration: 4.402 seconds
```

**Comment by craigfowler** [comment]
Looks like this is an easy fix if I just stop using `nameof`. It's a problem because it's a C# 6 feature, but the CodeDOM compiler does not support C# 6.

**Comment by craigfowler** [comment]
This needs testing on Windows and marking resolved if it worked.

**Comment by craigfowler** [comment]
Confirmed fixed on a Windows box
