### ISSUE TITLE
Fix unit test failures under Windows

### ISSUE THREAD

**Issue by craigfowler** [csf-dev/ZPT-Sharp#216]
As of commit `a78fe4d30fdabf4fcae62db3fc6b71d107449f00`.

```
1) Failed : Test.CSF.Zpt.BatchRendering.TestBatchRenderer
One or more child tests had errors

2) Error : Test.CSF.Zpt.BatchRendering.TestBatchRenderer.GetContextConfigurator_does_not_add_documents_directory_when_path_is_null
System.ArgumentException : Expression of type 'System.Object' cannot be used for parameter of type 'System.IO.DirectoryInfo' of method 'Moq.Language.Flow.IReturnsResult`1[CSF.Zpt.BatchRendering.IRenderingJob] Returns(System.IO.DirectoryInfo)'
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at Moq.Linq.MockSetupsBuilder.ConvertToSetup(Expression targetObject, Expression left, Expression right)
   at Moq.Linq.MockSetupsBuilder.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Moq.Linq.MockSetupsBuilder.VisitMethodCall(MethodCallExpression node)
   at Moq.Linq.MockQueryable`1.Execute[TResult](Expression expression)
   at Test.CSF.Zpt.BatchRendering.TestBatchRenderer.GetContextConfigurator_does_not_add_documents_directory_when_path_is_null() in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt\BatchRendering\TestBatchRenderer.cs:line 116

3) Failed : Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.TestExpressionHostCompiler
One or more child tests had errors

4) Error : Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.TestExpressionHostCompiler.GetHostCreator_returns_expression_which_may_be_executed_with_complex_parameters
CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionException : The CSharp expression must be valid; there must not be any compilation errors raised.  Please check the validity of the expression code?
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.ExpressionHostCompiler.CheckNoCompilerErrors(CompilerResults result, ExpressionModel model, String code) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\Host\ExpressionHostCompiler.cs:line 176
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.ExpressionHostCompiler.CompileHostAssembly(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\Host\ExpressionHostCompiler.cs:line 101
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.ExpressionHostCompiler.GetHostCreator(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\Host\ExpressionHostCompiler.cs:line 53
   at Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.TestExpressionHostCompiler.ExerciseSut(ExpressionModel model, IDictionary`2 variables) in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions\Host\TestExpressionHostCompiler.cs:line 215
   at Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.TestExpressionHostCompiler.GetHostCreator_returns_expression_which_may_be_executed_with_complex_parameters() in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions\Host\TestExpressionHostCompiler.cs:line 137

5) Error : Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.TestExpressionHostCompiler.GetHostCreator_returns_expression_which_may_be_executed_with_some_parameters
CSF.Zpt.ExpressionEvaluators.CSharpExpressions.CSharpExpressionException : The CSharp expression must be valid; there must not be any compilation errors raised.  Please check the validity of the expression code?
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.ExpressionHostCompiler.CheckNoCompilerErrors(CompilerResults result, ExpressionModel model, String code) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\Host\ExpressionHostCompiler.cs:line 176
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.ExpressionHostCompiler.CompileHostAssembly(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\Host\ExpressionHostCompiler.cs:line 101
   at CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.ExpressionHostCompiler.GetHostCreator(ExpressionModel model) in C:\repos\ZPT-Sharp\ExpressionEvaluators\CSF.Zpt.ExpressionEvaluators.CSharpExpressions\Host\ExpressionHostCompiler.cs:line 53
   at Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.TestExpressionHostCompiler.ExerciseSut(ExpressionModel model, IDictionary`2 variables) in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions\Host\TestExpressionHostCompiler.cs:line 215
   at Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions.Host.TestExpressionHostCompiler.GetHostCreator_returns_expression_which_may_be_executed_with_some_parameters() in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt.ExpressionEvaluators.CSharpExpressions\Host\TestExpressionHostCompiler.cs:line 113

6) Failed : Test.CSF.Zpt.Integration.ZptIntegrationTests
One or more child tests had errors

7) Failed : Test.CSF.Zpt.Integration.ZptIntegrationTests.RunIntegrationTests
  Out of 50 integration tests, 1 failed. See the log file for more info.
  Expected: True
  But was:  False
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Integration.ZptIntegrationTests.RunIntegrationTests() in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt.Integration\ZptIntegrationTests.cs:line 39

Test Run Summary
  Overall result: Failed
  Test Count: 383, Passed: 379, Failed: 4, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 1, Errors: 3, Invalid: 0
  Start time: 2017-02-21 19:35:29Z
    End time: 2017-02-21 19:35:39Z
    Duration: 9.256 seconds
```

**Comment by craigfowler** [comment]
[These log files](https://github.com/csf-dev/ZPT-Sharp/files/791295/Test.logs.zip) were produced from the unit test run above.

**Comment by craigfowler** [comment]
As of commit `9d05e8f30c023a69c1f44cb4f3da3e7cdfc8a505`:

```
1) Failed : Test.CSF.Zpt.BatchRendering.TestBatchRenderer
One or more child tests had errors

2) Error : Test.CSF.Zpt.BatchRendering.TestBatchRenderer.GetContextConfigurator_does_not_add_documents_directory_when_path_is_null
System.ArgumentException : Expression of type 'System.Object' cannot be used for parameter of type 'System.IO.DirectoryInfo' of method 'Moq.Language.Flow.IReturnsResult`1[CSF.Zpt.BatchRendering.IRenderingJob] Returns(System.IO.DirectoryInfo)'
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at Moq.Linq.MockSetupsBuilder.ConvertToSetup(Expression targetObject, Expression left, Expression right)
   at Moq.Linq.MockSetupsBuilder.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Moq.Linq.MockSetupsBuilder.VisitMethodCall(MethodCallExpression node)
   at Moq.Linq.MockQueryable`1.Execute[TResult](Expression expression)
   at Test.CSF.Zpt.BatchRendering.TestBatchRenderer.GetContextConfigurator_does_not_add_documents_directory_when_path_is_null() in C:\repos\ZPT-Sharp\Tests\Test.CSF.Zpt\BatchRendering\TestBatchRenderer.cs:line 116

Test Run Summary
  Overall result: Failed
  Test Count: 383, Passed: 382, Failed: 1, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 0, Errors: 1, Invalid: 0
  Start time: 2017-02-21 19:40:06Z
    End time: 2017-02-21 19:40:10Z
    Duration: 4.812 seconds
```
