### ISSUE TITLE
Errors encountered when building & testing on MS Wnidows

### ISSUE THREAD

**Issue by craigfowler** [csf-dev/ZPT-Sharp#43]
```
Time Elapsed 00:00:00.44
NUnit Console Runner 3.2.1
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10586.0
  CLR Version: 4.0.30319.42000

Test Files
    CSF.Zpt.nunit


Errors and Failures

1) Failed : Test.CSF.Zpt.Metal.MetalVisitorIntegrationTests
One or more child tests had errors

2) Failed : Test.CSF.Zpt.Metal.MetalVisitorIntegrationTests.TestVisitRoot
  Expected string length 488 but was 504. Strings differ at index 43.
  Expected: "...http://ns.csf-dev.com/sample">\n  <ele>\n    <base>Base cont..."
  But was:  "...http://ns.csf-dev.com/sample">\r\n  <ele>\r\n    <base>Base co..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Metal.MetalVisitorIntegrationTests.TestVisitRoot() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Metal\MetalVisitorIntegrationTests.cs:line 118

3) Failed : Test.CSF.Zpt.Metal.TestMacroFinder
One or more child tests had errors

4) Error : Test.CSF.Zpt.Metal.TestMacroFinder.TestGetExtendedMacroNoAttribute
System.ArgumentException : Expression of type 'System.Object' cannot be used for parameter of type 'CSF.Zpt.Rendering.ZptAttribute' of method 'Moq.Language.Flow.IReturnsResult`1[CSF.Zpt.Rendering.ZptElement] Returns(CSF.Zpt.Rendering.ZptAttribute)'
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at Moq.Linq.MockSetupsBuilder.ConvertToSetup(Expression targetObject, Expression left, Expression right)
   at Moq.Linq.MockSetupsBuilder.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Moq.Linq.MockSetupsBuilder.VisitMethodCall(MethodCallExpression node)
   at Moq.Linq.MockQueryable`1.Execute[TResult](Expression expression)
   at Test.CSF.Zpt.Metal.TestMacroFinder.TestGetExtendedMacroNoAttribute() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Metal\TestMacroFinder.cs:line 166

5) Error : Test.CSF.Zpt.Metal.TestMacroFinder.TestGetUsedMacroNoAttribute
System.ArgumentException : Expression of type 'System.Object' cannot be used for parameter of type 'CSF.Zpt.Rendering.ZptAttribute' of method 'Moq.Language.Flow.IReturnsResult`1[CSF.Zpt.Rendering.ZptElement] Returns(CSF.Zpt.Rendering.ZptAttribute)'
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at Moq.Linq.MockSetupsBuilder.ConvertToSetup(Expression targetObject, Expression left, Expression right)
   at Moq.Linq.MockSetupsBuilder.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Moq.Linq.MockSetupsBuilder.VisitMethodCall(MethodCallExpression node)
   at Moq.Linq.MockQueryable`1.Execute[TResult](Expression expression)
   at Test.CSF.Zpt.Metal.TestMacroFinder.TestGetUsedMacroNoAttribute() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Metal\TestMacroFinder.cs:line 92

6) Failed : Test.CSF.Zpt.Rendering.TestZptHtmlElement
One or more child tests had errors

7) Failed : Test.CSF.Zpt.Rendering.TestZptHtmlElement.TestInsertBefore
  Correct modified HTML
  Expected string length 549 but was 551. Strings differ at index 235.
  Expected: "...li>\n      <li>New element</li>\n      <li custom:child_attr..."
  But was:  "...li>\n      <li>New element</li>\r\n\n      <li custom:child_at..."
  ----------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptHtmlElement.TestInsertBefore() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptHtmlElement.cs:line 533

8) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement
One or more child tests had errors

9) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestAddCommentBefore
  Expected string length 671 but was 693. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestAddCommentBefore() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 670

10) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestInsertAfter
  Correct modified XML
  Expected string length 677 but was 699. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestInsertAfter() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 606

11) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestInsertBefore
  Correct modified XML
  Expected string length 677 but was 699. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestInsertBefore() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 555

12) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestOmit
  Correct modified XML
  Expected string length 540 but was 559. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestOmit() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 740

13) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestPurgeAttributes
  Correct modified XML
  Expected string length 525 but was 546. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestPurgeAttributes() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 322

14) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestRemoveAttribute
  Correct modified XML
  Expected string length 618 but was 639. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestRemoveAttribute() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 242

15) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestRemoveAttributeWithNamespace
  Correct modified XML
  Expected string length 603 but was 624. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestRemoveAttributeWithNamespace() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 282

16) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestReplaceChildrenWithString
  Correct modified XML
  Expected string length 479 but was 494. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestReplaceChildrenWithString() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 468

17) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestReplaceChildrenWithStringStructure
  Correct modified XML
  Expected string length 500 but was 517. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestReplaceChildrenWithStringStructure() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 504

18) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestReplaceWith
  Correct modified XML
  Expected string length 385 but was 400. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestReplaceWith() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 363

19) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestReplaceWithString
  Correct modified XML
  Expected string length 390 but was 404. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestReplaceWithString() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 398

20) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestReplaceWithStringStructure
  Correct modified XML
  Expected string length 402 but was 417. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestReplaceWithStringStructure() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 434

21) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestSetAttribute
  Correct modified XML
  Expected string length 656 but was 677. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestSetAttribute() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 162

22) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestSetAttributeWithNamespace
  Correct modified XML
  Expected string length 700 but was 721. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestSetAttributeWithNamespace() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 202

23) Failed : Test.CSF.Zpt.Rendering.TestZptXmlElement.TestToString
  Expected string length 646 but was 667. Strings differ at index 50.
  Expected: "...http://ns.csf-dev.com/custom">\n  <head>\n    <title>Documen..."
  But was:  "...http://ns.csf-dev.com/custom">\r\n  <head>\r\n    <title>Docum..."
  ---------------------------------------------^
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.Rendering.TestZptXmlElement.TestToString() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\Rendering\TestZptXmlElement.cs:line 55

24) Failed : Test.CSF.Zpt.SourceAnnotationIntegrationTests
One or more child tests had errors

25) Failed : Test.CSF.Zpt.SourceAnnotationIntegrationTests.RunIntegrationTests
  Out of 7 integration tests, 7 failed. See the log file for more info.
  Expected: True
  But was:  False
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.SourceAnnotationIntegrationTests.RunIntegrationTests() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\SourceAnnotationIntegrationTests.cs:line 72

26) Failed : Test.CSF.Zpt.ZptIntegrationTests
One or more child tests had errors

27) Failed : Test.CSF.Zpt.ZptIntegrationTests.RunIntegrationTests
  Out of 43 integration tests, 14 failed. See the log file for more info.
  Expected: True
  But was:  False
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Test.CSF.Zpt.ZptIntegrationTests.RunIntegrationTests() in C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\Test.CSF.Zpt\ZptIntegrationTests.cs:line 73

Test Run Summary
  Overall result: Failed
  Test Count: 247, Passed: 226, Failed: 21, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 19, Errors: 2, Invalid: 0
  Start time: 2016-06-17 12:02:03Z
    End time: 2016-06-17 12:02:07Z
    Duration: 4.242 seconds
```

**Comment by craigfowler** [comment]
These are now all fixed
